<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ETAM.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <!-- Donne accès à IHttpContextAccessor et aux types ASP.NET Core depuis cette bibliothèque -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="Hangfire.Core" Version="1.8.14" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.9" />
    <PackageReference Include="Serilog" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ETAM.Application\ETAM.Application.csproj" />
    <ProjectReference Include="..\ETAM.Domain\ETAM.Domain.csproj" />
  </ItemGroup>
</Project>
