using ETAM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ETAM.Infrastructure.Migrations
{
    /// <summary>
    /// Rattrapage : crée les tables des rapports de travail si elles n'existent pas.
    /// Elles avaient été créées manuellement sur la base de développement, mais la migration
    /// correspondante avait été neutralisée — elles manquaient donc sur toute base neuve
    /// (production). « IF NOT EXISTS » rend cette migration sans effet là où elles existent déjà.
    /// </summary>
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727120000_RattrapageRapportsTravail")]
    public partial class RattrapageRapportsTravail : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""RapportsTravail"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""ChantierId"" bigint NOT NULL,
    ""Numero"" character varying(20) NOT NULL,
    ""PeriodeDebut"" timestamp with time zone NOT NULL,
    ""PeriodeFin"" timestamp with time zone NOT NULL,
    ""Lieu"" character varying(200),
    ""EntrepriseExecutante"" character varying(150),
    ""ConducteurTravaux"" character varying(150),
    ""EffectifCadres"" integer NOT NULL DEFAULT 0,
    ""EffectifOuvriers"" integer NOT NULL DEFAULT 0,
    ""HoraireMatin"" character varying(50),
    ""HoraireApresMidi"" character varying(50),
    ""ConditionsMeteo"" character varying(300),
    ""ResumeSuiviPlanning"" text,
    ""ProblemesRencontres"" text,
    ""Suggestions"" text,
    ""Statut"" integer NOT NULL DEFAULT 0,
    ""SoumisPar"" text,
    ""DateSoumission"" timestamp with time zone,
    ""ValideParId"" text,
    ""DateValidation"" timestamp with time zone,
    ""MotifRefus"" character varying(500),
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
    ""UpdatedAt"" timestamp with time zone,
    ""CreatedBy"" text,
    ""UpdatedBy"" text,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    CONSTRAINT ""PK_RapportsTravail"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_RapportsTravail_Chantiers_ChantierId"" FOREIGN KEY (""ChantierId"")
        REFERENCES ""Chantiers"" (""Id"") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ""RapportTravailLignesAvancement"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""RapportTravailId"" bigint NOT NULL,
    ""Zone"" character varying(150) NOT NULL,
    ""TravauxRealises"" text NOT NULL,
    ""NiveauAvancement"" character varying(150) NOT NULL,
    ""Observations"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
    ""UpdatedAt"" timestamp with time zone,
    ""CreatedBy"" text,
    ""UpdatedBy"" text,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    CONSTRAINT ""PK_RapportTravailLignesAvancement"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_RapportTravailLignesAvancement_RapportsTravail_RapportTrava~""
        FOREIGN KEY (""RapportTravailId"") REFERENCES ""RapportsTravail"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""RapportTravailLignesEquipements"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""RapportTravailId"" bigint NOT NULL,
    ""Equipement"" character varying(150) NOT NULL,
    ""Etat"" character varying(80),
    ""Observation"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
    ""UpdatedAt"" timestamp with time zone,
    ""CreatedBy"" text,
    ""UpdatedBy"" text,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    CONSTRAINT ""PK_RapportTravailLignesEquipements"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_RapportTravailLignesEquipements_RapportsTravail_RapportTrav~""
        FOREIGN KEY (""RapportTravailId"") REFERENCES ""RapportsTravail"" (""Id"") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ""RapportTravailLignesMateriaux"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""RapportTravailId"" bigint NOT NULL,
    ""Materiau"" character varying(150) NOT NULL,
    ""Unite"" character varying(20),
    ""QuantiteUtilisee"" numeric(18,3) NOT NULL DEFAULT 0,
    ""StockInitial"" numeric(18,3) NOT NULL DEFAULT 0,
    ""Entree"" numeric(18,3) NOT NULL DEFAULT 0,
    ""StockRestant"" numeric(18,3) NOT NULL DEFAULT 0,
    ""Observations"" text,
    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
    ""UpdatedAt"" timestamp with time zone,
    ""CreatedBy"" text,
    ""UpdatedBy"" text,
    ""IsDeleted"" boolean NOT NULL DEFAULT false,
    CONSTRAINT ""PK_RapportTravailLignesMateriaux"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_RapportTravailLignesMateriaux_RapportsTravail_RapportTravai~""
        FOREIGN KEY (""RapportTravailId"") REFERENCES ""RapportsTravail"" (""Id"") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ""IX_RapportsTravail_ChantierId_PeriodeFin""
    ON ""RapportsTravail"" (""ChantierId"", ""PeriodeFin"");
CREATE INDEX IF NOT EXISTS ""IX_RapportsTravail_Statut""
    ON ""RapportsTravail"" (""Statut"");
CREATE INDEX IF NOT EXISTS ""IX_RapportTravailLignesAvancement_RapportTravailId""
    ON ""RapportTravailLignesAvancement"" (""RapportTravailId"");
CREATE INDEX IF NOT EXISTS ""IX_RapportTravailLignesEquipements_RapportTravailId""
    ON ""RapportTravailLignesEquipements"" (""RapportTravailId"");
CREATE INDEX IF NOT EXISTS ""IX_RapportTravailLignesMateriaux_RapportTravailId""
    ON ""RapportTravailLignesMateriaux"" (""RapportTravailId"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DROP TABLE IF EXISTS ""RapportTravailLignesAvancement"";
DROP TABLE IF EXISTS ""RapportTravailLignesEquipements"";
DROP TABLE IF EXISTS ""RapportTravailLignesMateriaux"";
DROP TABLE IF EXISTS ""RapportsTravail"";
");
        }
    }
}
